name: Deploy PDF Translator Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3

      - name: Run setup script
        run: ./setup.sh

      - name: Publish Lambda version (StatusCheckerFunction)
        id: publish_status_version
        run: |
          VERSION=$(aws lambda publish-version \
            --function-name status-checker-417404104136-v2 \
            --region eu-west-3 \
            --query 'Version' \
            --output text)
          echo "Published version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Update prod alias (StatusCheckerFunction)
        run: |
          aws lambda update-alias \
            --function-name status-checker-417404104136-v2 \
            --name prod \
            --region eu-west-3 \
            --function-version "${{ steps.publish_status_version.outputs.version }}"
        
